spring.application.name=Apple-Vision-Mobile-Shop
spring.datasource.url=jdbc:mysql://localhost:3306/apple_vision_mobile_shop?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true